# Approved journal list from UpToDate: https://www.wolterskluwer.com/en/solutions/uptodate/about/evidence-based-medicine/journals-reviewed-by-uptodate
# Manually adapted to match the journal names in the PMC dataset

APPROVED_JOURNALS = [
    "AAP Grand Rounds",
    "AAP Policy",
    "Academic Emergency Medicine",
    "ACP Journal Club",
    "Acta Anaesthesiologica Scandinavica",
    "Acta Obstetricia et Gynecologica Scandinavica",
    "Addiction",
    "Advances in Chronic Kidney Diseases",
    "Adverse Drug Reaction Bulletin",
    "AHRQ",
    "AIDS",
    "Alimentary Pharmacology and Therapeutics",
    "Allergy",
    "American Heart Journal",
    "American Journal of Cardiology",
    "American Journal of Clinical Nutrition",
    "American Journal of Clinical Oncology",
    "American Journal of Emergency Medicine",
    "American Journal of Epidemiology",
    "American Journal of Gastroenterology",
    "American Journal of Health System Pharmacy",
    "American Journal of Hematology",
    "American Journal of Hospice and Palliative Medicine",
    "American Journal of Human Genetics",
    "American Journal of Kidney Diseases",
    "American Journal of Medical Genetics. Part A",
    "American Journal of Medicine",
    "American Journal of Obstetrics & Gynecology MFM",
    "American Journal of Obstetrics and Gynecology",
    "American Journal of Ophthalmology",
    "American Journal of Psychiatry",
    "American Journal of Public Health",
    "American Journal of Respiratory and Critical Care Medicine",
    "American Journal of Rhinology & Allergy",
    "AJR. American journal of roentgenology",
    "American Journal of Sports Medicine",
    "American Journal of Surgery",
    "American Journal of Transplantation",
    "American Journal of Tropical Medicine and Hygiene",
    "Anaesthesia",
    "Anesthesia and Analgesia",
    "Anesthesiology",
    "Annals of Allergy, Asthma & Immunology",
    "Annals of Emergency Medicine",
    "Annals of Family Medicine",
    "Annals of Internal Medicine",
    "Annals of Neurology",
    "Annals of Oncology",
    "Annals of Pharmacotherapy",
    "Annals of Surgery",
    "Annals of Surgical Oncology",
    "Annals of the American Thoracic Society",
    "Annals of the Rheumatic Diseases",
    "Annals of Thoracic Surgery",
    "Annals of Vascular Surgery",
    "Antimicrobial Agents and Chemotherapy",
    "Archives of Disease in Childhood",
    "Archives of Disease in Childhood: Fetal and Neonatal Edition",
    "Arthritis & Rheumatology",
    "Arthritis Care and Research",
    "Australian and New Zealand Journal of Obstetrics and Gynaecology",
    "Best practice & research. Clinical endocrinology & metabolism",
    "Best Practice & Research: Clinical Obstetrics & Gynaecology",
    "Bipolar Disorders",
    "Birth Defects Research",
    "BJOG: an International Journal of Obstetrics and Gynaecology",
    "Blood",
    "Blood Advances",
    "BMC Palliative Care",
    "BMJ Open Gastroenterology",
    "BMJ Supportive & Palliative Care",
    "Bone Marrow Transplantation",
    "Brain",
    "Breast Journal",
    "British Journal of Anaesthesia",
    "British Journal of Cancer",
    "British Journal of Dermatology",
    "British Journal of Haematology",
    "British Journal of Ophthalmology",
    "British Journal of Psychiatry",
    "British Journal of Sports Medicine",
    "British Journal of Surgery",
    "British medical journal",
    "CA: A Cancer Journal for Clinicians",
    "Canadian Journal of Anesthesia/Journal canadien d'anesth\u00e9sie",
    "Canadian Journal of Anaesthesia-journal Canadien D Anesthesie"
    "Canadian Medical Association journal",
    "Canadian Medical Association Journal",
    "CMAJ Open",
    "Cancer",
    "Cancer Investigation",
    "Cancer Research",
    "Cephalalgia",
    "Chest",
    "Circulation",
    "Circulation: Arrhythmia and Electrophysiology",
    "Circulation: Cardiovascular Imaging",
    "Circulation: Cardiovascular Interventions",
    "Circulation. Cardiovascular Quality and Outcomes",
    "Circulation: Genomic and Precision Medicine",
    "Circulation: Heart Failure",
    "Climacteric",
    "Clinical Cancer Research",
    "Clinical Endocrinology",
    "Clinical Gastroenterology and Hepatology",
    "Clinical Genitourinary Cancer",
    "Clinical Immunology",
    "Clinical Infectious Diseases",
    "Clinical Journal of Sports Medicine",
    "Clinical Journal of the American Society of Nephrology (CJASN)",
    "Clinical Lymphoma, Myeloma & Leukemia",
    "Clinical Microbiology and Infection",
    "Clinical Microbiology Reviews",
    "Clinical Nephrology",
    "Clinical Pharmacokinetics",
    "Clinical Pharmacology and Therapeutics",
    "Clinical Toxicology",
    "Clinics in Chest Medicine",
    "CNS Drugs",
    "Cochrane Library",
    "Continuum: Lifelong Learning in Neurology",
    "Contraception",
    "Critical Care Medicine",
    "Critical Pathways in Cardiology",
    "Current Opinion in Anaesthesiology",
    "Current Opinion in Critical Care",
    "Current Opinion in Hematology",
    "Current Opinion in Infectious Diseases",
    "Current Opinion in Nephrology and Hypertension",
    "Current Opinion in Organ Transplantation",
    "Current Opinion in Pulmonary Medicine",
    "Current Opinion in Rheumatology",
    "Dermatologic Surgery",
    "Developmental Medicine and Child Neurology",
    "Diabetes",
    "Diabetes Care",
    "Diabetologia",
    "Diseases of the Colon and Rectum",
    "Drug and Alcohol Dependence",
    "Drug Safety",
    "Drugs",
    "Drugs & Aging",
    "Emerging Infectious Diseases",
    "Endocrine Practice",
    "Endocrine Reviews",
    "Endocrinology",
    "Endocrinology Metabolism Clinics of North America",
    "Endoscopy",
    "Epilepsia",
    "Epilepsy and Behavior",
    "Europace",
    "European Heart Journal",
    "European Journal of Anaesthesiology",
    "European Journal of Cancer",
    "European Journal of Cardiothoracic Surgery",
    "European Journal of Endocrinology",
    "European Journal of Obstetrics & Gynecology and Reproductive Biology",
    "European Journal of Pediatrics",
    "European Radiology",
    "European Respiratory Journal",
    "European Respiratory Review",
    "European Urology",
    "FDA Digest",
    "Female Pelvic Medicine & Reconstructive Surgery",
    "Fertility and Sterility",
    "Gastroenterology",
    "Gastrointestinal Endoscopy",
    "Genetics in Medicine",
    "Gut",
    "Gynecologic Oncology",
    "Haematologica",
    "Head and Neck",
    "Heart",
    "Heart Rhythm",
    "Hemodialysis International",
    "Hemophilia",
    "Hepatology",
    "Human Molecular Genetics",
    "Human Reproduction",
    "Human Reproduction Update",
    "Hypertension",
    "Hypertension in Pregnancy",
    "Immunology and Allergy Clinics of North America",
    "Infection Control and Hospital Epidemiology",
    "Infectious Disease Clinics of North America",
    "Inflammatory Bowel Diseases",
    "Integrative Medicine Alert",
    "Intensive Care Medicine",
    "International Journal of Artificial Organs",
    "International Journal of Cancer",
    "International Journal of Eating Disorders",
    "International Journal of Gynecological Cancer",
    "International Journal of Obesity",
    "International Journal of Obstetric Anesthesia",
    "International Journal of Radiation Oncology Biology Physics",
    "International Journal of Tuberculosis and Lung Disease",
    "International Urogynecology Journal",
    "JACC: Cardiovascular Imaging",
    "JACC: Cardiovascular Interventions",
    "JACC: Clinical Electrophysiology",
    "JACC: Heart Failure",
    "Journal of Acquired Immune Deficiency Syndromes",
    "JAMA Cardiology",
    "JAMA Dermatology",
    "JAMA Internal Medicine",
    "JAMA Oncology",
    "JAMA Ophthalmology",
    "JAMA Pediatrics",
    "JAMA Psychiatry",
    "JAMA Surgery",
    "JCO Precision Oncology",
    "Journal for Immunotherapy of Cancer",
    "Journal of Addiction Medicine",
    "Journal of Adolescent Health",
    "Journal of Affective Disorders",
    "Journal of Allergy and Clinical Immunology",
    "Journal of Allergy and Clinical Immunology: In Practice",
    "Journal of Antimicrobial Chemotherapy",
    "Journal of Anxiety Disorders",
    "Journal of Bone and Joint Surgery, American volume",
    "Journal of Bone and Mineral Research",
    "Journal of Cancer Research and Clinical Oncology",
    "Journal of Cancer Survivorship",
    "Journal of Cardiac Failure",
    "Journal of Cardiothoracic and Vascular Anesthesia",
    "Journal of Cardiovascular Electrophysiology, The",
    "Journal of Child Neurology",
    "Journal of Clinical Anesthesia",
    "Journal of Clinical Endocrinology and Metabolism",
    "Journal of Clinical Microbiology",
    "Journal of Clinical Oncology",
    "Journal of Clinical Psychiatry",
    "Journal of Clinical Sleep Medicine (JCSM)",
    "Journal of Dental Research",
    "Journal of Developmental and Behavioral Pediatrics",
    "Journal of Emergency Medicine",
    "Journal of Gastrointestinal Surgery",
    "Journal of general internal medicine",
    "The Journal of Heart and Lung Transplantation",
    "Journal of Hepatology",
    "Journal of Hospital Medicine",
    "Journal of Hypertension",
    "Journal of Infectious Diseases",
    "Journal of Inherited Metabolic Disease",
    "Journal of Intensive Care Medicine",
    "Journal of Investigative Dermatology",
    "Journal of Lower Genital Tract Disease",
    "Journal of Minimally Invasive Gynecology",
    "Journal of Neurology, Neurosurgery, and Psychiatry",
    "Journal of Neuro-Oncology",
    "Journal of Neurosurgery",
    "Journal of Oncology Practice",
    "Journal of Pain and Symptom Management",
    "Journal of Pain",
    "Journal of Palliative Care",
    "Journal of Palliative Medicine",
    "Journal of Parenteral and Enteral Nutrition",
    "Journal of Pediatric and Adolescent Gynecology",
    "Journal of Pediatric Endocrinology & Metabolism",
    "Journal of Pediatric Gastroenterology and Nutrition",
    "Journal of Pediatric Orthopaedics",
    "Journal of Pediatric Surgery",
    "Journal of Pediatrics",
    "Journal of Perinatology",
    "Journal of Personality Disorders",
    "Journal of Renal Nutrition",
    "Journal of Rheumatology",
    "Journal of Sexual Medicine",
    "Journal of Sleep Research",
    "Journal of Strength and Conditioning Research",
    "Journal of Surgical Oncology",
    "Journal of the American Academy of Child and Adolescent Psychiatry",
    "Journal of the American Academy of Dermatology",
    "Journal of the American College of Cardiology",
    "Journal of the American College of Radiology",
    "Journal of the American College of Surgeons",
    "The Journal of the American Dental Association (1939)",
    "Journal of the American Geriatrics Society",
    "Journal of the American Heart Association : Cardiovascular and Cerebrovascular Disease",
    "Journal of the American Medical Association (JAMA)",
    "Journal of the American Society of Echocardiography",
    "Journal of the American Society of Nephrology",
    "Journal of the Endocrine Society",
    "Journal of the European Academy of Dermatology and Venereology",
    "JNCI Journal of the National Cancer Institute",
    "Journal of the National Comprehensive Cancer Network",
    "Journal of the Pediatrics Infectious Diseases Society",
    "Journal of Thoracic and Cardiovascular Surgery",
    "Journal of Thoracic Oncology",
    "Journal of Thrombosis and Haemostasis",
    "Journal of Trauma and Acute Care Surgery",
    "Journal of Ultrasound in Medicine",
    "Journal of Urology",
    "Journal of Vascular Surgery",
    "Journal Watch: Emergency Medicine",
    "Journal Watch: Infectious Diseases",
    "Journal Watch: Neurology",
    "Journal Watch: Oncology and Hematology",
    "Journal Watch: Psychiatry",
    "Kidney International",
    "Kidney International Reports",
    "Kidney360",
    "The Lancet Child & Adolescent Health",
    "The Lancet Gastroenterology and Hepatology",
    "Lancet Global Health",
    "Lancet Infectious Diseases",
    "Lancet Neurology",
    "The Lancet Oncology",
    "The Lancet Respiratory Medicine",
    "Lancet Rheumatology",
    "The Lancet Rheumatology",
    "The Laryngoscope",
    "Leukemia",
    "Leukemia Lymphoma",
    "LGBT Health",
    "Liver Transplantation",
    "Lung Cancer",
    "Lupus",
    "Malaria Journal",
    "Maturitas",
    "Mayo Clinic Proceedings",
    "Medical Clinics of North America",
    "Medical Letter, The",
    "Medicine and Science in Sports and Exercise",
    "Melanoma Research",
    "Menopause",
    "Menopause: The Journal of the North American Menopause Society",
    "MMWR. Morbidity and mortality weekly report",
    "Movement Disorders",
    "Muscle & Nerve",
    "Nature",
    "Nature Genetics",
    "Nature Medicine",
    "Nature Reviews Cancer",
    "Nature Reviews Clinical Oncology",
    "Nature Reviews Nephrology",
    "Nature Reviews Rheumatology",
    "Nephrology Dialysis Transplantation",
    "Neurocritical Care",
    "Neuroimmunology & Neuroinflammation",
    "Neurology",
    "Neurology Alert",
    "Neuro-Oncology",
    "New England Journal of Medicine",
    "Obstetrics & Gynecology",
    "Oncologist, The",
    "Open Forum Infectious Diseases",
    "Ophthalmology",
    "Osteoporosis International",
    "Pacing and Clinical Electrophysiology",
    "Paediatrics & Child Health",
    "Pain Medicine",
    "Palliative & Supportive Care",
    "Palliative Medicine",
    "Pancreas",
    "Pediatric Allergy and Immunology",
    "Pediatric Anesthesia",
    "Pediatric Blood and Cancer",
    "Pediatric Cardiology",
    "Pediatric Critical Care Medicine",
    "Pediatric Dermatology",
    "Pediatric Diabetes",
    "Pediatric Drugs",
    "Pediatric Emergency Care",
    "Pediatric Infectious Disease Journal",
    "Pediatric Nephrology",
    "Pediatric Neurology",
    "Pediatric Pulmonology",
    "Pediatric Radiology",
    "Pediatric Research",
    "Pediatrics",
    "Peritoneal Dialysis International",
    "Pharmacology and Therapeutics",
    "Pharmacotherapy",
    "PLoS Medicine",
    "PLOS One: Obstetrics and Gynecology",
    "PLOS One: Rheumatology",
    "Post Reproductive Health",
    "Prenatal Diagnosis",
    "Psychiatric Services",
    "Psychiatry Drug Alerts",
    "Psychological Medicine",
    "QJM: An International Journal of Medicine",
    "Radiology",
    "Radiotherapy and Oncology",
    "Red Book Online",
    "Regional Anesthesia and Pain Medicine",
    "Reproductive Medicine and Biology",
    "Resuscitation",
    "Rheumatology",
    "Schizophrenia Bulletin",
    "Science",
    "Seminars in Dialysis",
    "Seminars in Hematology",
    "Seminars in Nephrology",
    "Sexually Transmitted Diseases",
    "Shock",
    "Sleep",
    "Sleep Medicine",
    "Sleep Medicine Review",
    "Spine",
    "Stroke",
    "Supportive Care in Cancer",
    "Surgery",
    "Surgery for Obesity and Related Diseases",
    "Surgical Endoscopy",
    "The Bone & Joint Journal",
    "Therapeutic Apheresis and Dialysis",
    "Therapeutic Drug Monitoring",
    "Thorax",
    "Thrombosis and Haemostasis",
    "Thyroid",
    "Transactions of the Royal Society of Tropical Medicine and Hygiene",
    "Transfusion",
    "Transgender Health",
    "Transplant Infectious Disease",
    "Transplantation Direct",
    "Ultrasound in Obstetrics & Gynecology",
    "Urologic Oncology: Seminars and Original Investigations",
    "Urology",
    "Vascular Medicine",
    "WHO Pharmaceuticals NEWSLETTER",
    "Wilderness & Environmental Medicine",
    "World Journal of Emergency Surgery"
]

translation = {ord(ch): '' for ch in ":,.-"}
APPROVED_JOURNALS = [journal.lower().replace("&", "and").translate(translation) for journal in APPROVED_JOURNALS]
